name: build-application

on:
  push:
    branches: [ main, feature/* ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # restore dependencies
    - name: Install dependencies
      run: dotnet restore
    # build application
    - name: Build application
      run: dotnet build
    # run unit tests, save tests results as xml file, and publish results as artifact
    - name: Run unit tests
      run: dotnet test --logger:"xunit;LogFilePath=/test-results/test-results.xml"
    - name: Publish test results
      uses: actions/artifact@v2
      with:
        name: test-results.xml
        path: /test-results



    


      
    





    