name: build-application

on:
  push:
    branches: [ main, feature/* ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build application
      run: dotnet build
    - name: Run unit tests
      run: dotnet test --logger "xunit;LogFileName=unit-tests-results.xml"
    - name: Upload unit test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: "**/*.xml"



    


      
    





    