name: build-application

on:
  push:
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
       
    - name: Install dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore  
    # run unit tests and upload test results to github actions
    - name: Test and upload test results
      run: dotnet test --configuration Release --no-restore --logger "xunit;LogFileName=test-results.xml"
    # upload test results to github actions
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: test-results.xml
        path: test-results.xml
        target-path: test-results.xml

