name: build-application

on:
  push:
    branches: [ main, feature/* ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # restore dependencies
    - name: Install dependencies
      run: dotnet restore
    # build application
    - name: Build application
      run: dotnet build
      
    





    