name: build-application

on:
  push:
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
       
    - name: Install dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore    
    # run unit tests and save resutls as xml and  upload to github actions
    - name: Unit tests
      run: dotnet test --configuration Release --no-restore --logger:"xunit;LogFilePath=./test-results.xml"
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: test-results.xml
        path: test-results.xml



